/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbasesav_p1;

import com.sun.org.apache.xerces.internal.xs.StringList;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import structures.Investigador;

/**
 *
 * @author Cousik94
 */
public class Investigadores extends javax.swing.JFrame {

    public TableModel modelClickR;

    Investigador[] invs;
    ArrayList<Investigador> invsSelec = new ArrayList<Investigador>();
    private  String nombre;
    private String ventajas;
    private  String antecedentes;
    private  String descripcion;
    private  String estatus;
    private  String aplicaciones;

    /**
     * Creates new form Investigadores0
     */
    public Investigadores( String nombre, String ventajas, String antecedentes, String descripcion, String estatus, String aplicaciones) {
        ArrayList<Investigadores> invest;
        this.nombre = nombre;
        this.ventajas = ventajas;
        this.antecedentes = antecedentes;
        this.descripcion = descripcion;
        this.estatus = estatus;
        this.aplicaciones = aplicaciones;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tablaResult = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSelec = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textInv = new javax.swing.JTextField();
        buscarInv = new javax.swing.JButton();
        logo = new javax.swing.JButton();
        Aplicar = new javax.swing.JButton();
        AgregarInv = new javax.swing.JButton();
        EliminarInv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaResult.setModel(new CustomTableModel("Resultados"));
        tablaResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaResultMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaResult);

        tablaSelec.setModel(new CustomTableModel("Resultados"));
        jScrollPane4.setViewportView(tablaSelec);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Agregar y eliminar investigadores al proyecto");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Investigador");

        textInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInvActionPerformed(evt);
            }
        });

        buscarInv.setText("Buscar");
        buscarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInvActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/logo2.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        Aplicar.setText("Aplicar Cambios");
        Aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarActionPerformed(evt);
            }
        });

        AgregarInv.setText("Agregar ->");
        AgregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInvActionPerformed(evt);
            }
        });

        EliminarInv.setText("<- Eliminar");
        EliminarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(buscarInv)
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(11, 11, 11)
                            .addComponent(textInv, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(340, 340, 340)
                            .addComponent(Aplicar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(330, 330, 330)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AgregarInv)
                                        .addComponent(EliminarInv))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(buscarInv)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel1)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Aplicar)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(textInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(AgregarInv)
                            .addGap(8, 8, 8)
                            .addComponent(EliminarInv))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInvActionPerformed

    private void buscarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInvActionPerformed
        // TODO add your handling code here:
        findInvestigador();
    }//GEN-LAST:event_buscarInvActionPerformed

    private void AgregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInvActionPerformed
        // TODO add your handling code here:
        int row = tablaResult.getSelectedRow();
        if (row != -1) {
            System.out.println(row);
            invsSelec.add(invs[row]);
            ((CustomTableModel) tablaSelec.getModel()).addRow(new Object[]{invs[row].toString()});

        }


    }//GEN-LAST:event_AgregarInvActionPerformed

    private void EliminarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarInvActionPerformed
        // TODO add your handling code here:
        int row = tablaSelec.getSelectedRow();
        if (row != -1) {

            invsSelec.remove(row);
            ((CustomTableModel) tablaSelec.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_EliminarInvActionPerformed

    private void tablaResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResultMouseClicked
        // TODO add your handling code here:
        int index = tablaResult.getSelectedRow();
        modelClickR = tablaResult.getModel();

    }//GEN-LAST:event_tablaResultMouseClicked

    private void AplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarActionPerformed
        // TODO add your handling code here:
        cambiarVentana(new Registro(nombre, ventajas, antecedentes, descripcion, estatus, aplicaciones, invsSelec));
    }//GEN-LAST:event_AplicarActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        cambiarVentana(new Start());
    }//GEN-LAST:event_logoActionPerformed
       public void cambiarVentana(JFrame frame) {
        frame.setVisible(true);
        this.dispose();
    }


//FUNCION SE LE PONE AL BOTON Y RECORRER ARRAY Y DEVUELVE RESULTADO     
    public void findInvestigador() {
        CustomTableModel model = null;
        try {
            Connection con = Conexion.getConexion();
            model = Conexion.createTableModel(con, "select nombre from Investigadores where nombre like ? ", new Object[]{"%" + textInv.getText() + "%"}, "investigadores no encontrados");
            invs = Conexion.rstoInvestigadores(con, "select * from Investigadores where nombre like ? ", new Object[]{"%" + textInv.getText() + "%"});
        } catch (SQLException ex) {
            Logger.getLogger(Investigadores.class.getName()).log(Level.SEVERE, null, ex);
        }

        tablaResult.setModel(model);

    }
//FUNCION EXCEC QUERY


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarInv;
    private javax.swing.JButton Aplicar;
    private javax.swing.JButton EliminarInv;
    private javax.swing.JButton buscarInv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logo;
    private javax.swing.JTable tablaResult;
    private javax.swing.JTable tablaSelec;
    private javax.swing.JTextField textInv;
    // End of variables declaration//GEN-END:variables

}
