/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbasesav_p1;

import javax.swing.JFrame;
import structures.Proyecto;
import pbasesav_p1.Start;

/**
 *
 * @author Soporte
 */
public class MostrarOT extends javax.swing.JFrame {

    public void cambiarVentana(JFrame frame) {
        frame.setVisible(true);
        this.dispose();
    }
    /**
     * Creates new form MostrarOT
     */
    public MostrarOT(Proyecto ProMostrar) {
        initComponents();
        NombreOT.setText(ProMostrar.toString());
        DescripcionOT.setText(ProMostrar.getDescripcion());
        EstatusOT.setText(ProMostrar.getEstatus());
        VentajasOT.setText(ProMostrar.getVentajas());
        AntecedenetesOT.setText(ProMostrar.getAntecedentes());
        ColaboradoresOT.setText(ProMostrar.getIdInvestigadores().toString());
        AplicacionesOT.setText(ProMostrar.getAplicaciones());
        
    }
    public MostrarOT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EstatusM = new javax.swing.JLabel();
        VentajasM = new javax.swing.JLabel();
        ColaboradoresM = new javax.swing.JLabel();
        AplicacionesM = new javax.swing.JLabel();
        logo = new javax.swing.JButton();
        AntecedentesM = new javax.swing.JLabel();
        NombreOT = new javax.swing.JLabel();
        DescripcionOT = new javax.swing.JLabel();
        NombreM = new javax.swing.JLabel();
        DescripcionM = new javax.swing.JLabel();
        VentajasOT = new javax.swing.JLabel();
        EstatusOT = new javax.swing.JLabel();
        ColaboradoresOT = new javax.swing.JLabel();
        AplicacionesOT = new javax.swing.JLabel();
        AntecedenetesOT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(627, 484));
        setPreferredSize(new java.awt.Dimension(627, 484));

        EstatusM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EstatusM.setText("Estatus");

        VentajasM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VentajasM.setText("Ventajas");

        ColaboradoresM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ColaboradoresM.setText("Colaboradores");

        AplicacionesM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AplicacionesM.setText("Aplicaciones");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/logo2.png"))); // NOI18N
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        AntecedentesM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AntecedentesM.setText("Antecedentes");

        NombreOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        NombreOT.setText("NombreOT");

        DescripcionOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        DescripcionOT.setText("DescripciónOT");

        NombreM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreM.setText("Nombre");

        DescripcionM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DescripcionM.setText("Descripción");

        VentajasOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        VentajasOT.setText("VentajasOT");

        EstatusOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        EstatusOT.setText("EstatusOT");

        ColaboradoresOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        ColaboradoresOT.setText("ColaboradoresOT");

        AplicacionesOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        AplicacionesOT.setText("AplicacionesOT");

        AntecedenetesOT.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        AntecedenetesOT.setText("AntecedentesOT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(logo))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreM)
                    .addComponent(DescripcionM)
                    .addComponent(EstatusM))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreOT, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripcionOT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstatusOT, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AntecedentesM)
                    .addComponent(ColaboradoresM))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AntecedenetesOT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColaboradoresOT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(VentajasM)
                .addGap(34, 34, 34)
                .addComponent(VentajasOT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(AplicacionesM)
                .addGap(31, 31, 31)
                .addComponent(AplicacionesOT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(logo)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(NombreM)
                        .addGap(47, 47, 47)
                        .addComponent(DescripcionM)
                        .addGap(32, 32, 32)
                        .addComponent(EstatusM))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NombreOT)
                        .addGap(7, 7, 7)
                        .addComponent(DescripcionOT, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(EstatusOT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(AntecedentesM)
                        .addGap(61, 61, 61)
                        .addComponent(ColaboradoresM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(AntecedenetesOT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(ColaboradoresOT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AplicacionesM)
                    .addComponent(AplicacionesOT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VentajasM)
                            .addComponent(VentajasOT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        cambiarVentana(new Start());                
    }//GEN-LAST:event_logoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarOT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AntecedenetesOT;
    private javax.swing.JLabel AntecedentesM;
    private javax.swing.JLabel AplicacionesM;
    private javax.swing.JLabel AplicacionesOT;
    private javax.swing.JLabel ColaboradoresM;
    private javax.swing.JLabel ColaboradoresOT;
    private javax.swing.JLabel DescripcionM;
    private javax.swing.JLabel DescripcionOT;
    private javax.swing.JLabel EstatusM;
    private javax.swing.JLabel EstatusOT;
    private javax.swing.JLabel NombreM;
    private javax.swing.JLabel NombreOT;
    private javax.swing.JLabel VentajasM;
    private javax.swing.JLabel VentajasOT;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
