/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbasesav_p1;

/**
 *
 * @author AdrianPineda
 */
public class OfertasTec extends javax.swing.JFrame {

    /**
     * Creates new form OfertasTec
     */
    public OfertasTec() {
        initComponents();
        limpiar();
       
    }

    
//Metodo de limpiar casillas
void limpiar(){
Nombre.setText("");
Descripcion.setText("");
Estatus.setText("");
Ventajas.setText("");
Antecedentes.setText("");
Aplicaciones.setText("");
Investigadores.setText("");
}    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Estatus = new javax.swing.JTextField();
        Investigadores = new javax.swing.JTextField();
        Aplicaciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Descripcion = new javax.swing.JTextField();
        Ventajas = new javax.swing.JTextField();
        Antecedentes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Nombre.setName("Nombre"); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre);
        Nombre.setBounds(140, 180, 272, 39);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion");
        jLabel1.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 270, 74, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estatus");
        jLabel10.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 360, 74, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Antecedentes");
        jLabel11.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 560, 90, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Investigadores");
        jLabel12.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 800, 90, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre");
        jLabel13.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 190, 74, 28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ventajas");
        jLabel14.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 450, 74, 28);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Aplicaciones");
        jLabel16.setPreferredSize(new java.awt.Dimension(74, 28));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 680, 74, 28);

        Estatus.setName("Estatus"); // NOI18N
        Estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstatusActionPerformed(evt);
            }
        });
        getContentPane().add(Estatus);
        Estatus.setBounds(140, 350, 272, 37);

        Investigadores.setName("Investigadores"); // NOI18N
        Investigadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvestigadoresActionPerformed(evt);
            }
        });
        getContentPane().add(Investigadores);
        Investigadores.setBounds(140, 770, 540, 100);

        Aplicaciones.setName("Aplicaciones"); // NOI18N
        Aplicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicacionesActionPerformed(evt);
            }
        });
        getContentPane().add(Aplicaciones);
        Aplicaciones.setBounds(140, 650, 540, 100);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 900, 90, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/IconoReturn.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(910, 0, 140, 140);

        Descripcion.setName("Descripcion"); // NOI18N
        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(Descripcion);
        Descripcion.setBounds(140, 240, 530, 90);

        Ventajas.setName("Ventajas"); // NOI18N
        Ventajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentajasActionPerformed(evt);
            }
        });
        getContentPane().add(Ventajas);
        Ventajas.setBounds(140, 410, 530, 100);

        Antecedentes.setName("Antecedentes"); // NOI18N
        Antecedentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntecedentesActionPerformed(evt);
            }
        });
        getContentPane().add(Antecedentes);
        Antecedentes.setBounds(140, 530, 540, 100);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/logo2.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 280, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbasesav_p1/background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1050, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
        Nombre.transferFocus();
    }//GEN-LAST:event_NombreActionPerformed

    private void EstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstatusActionPerformed
        // TODO add your handling code here:
        Estatus.transferFocus();
    }//GEN-LAST:event_EstatusActionPerformed

    private void InvestigadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvestigadoresActionPerformed
        // TODO add your handling code here:
        Investigadores.transferFocus();
    }//GEN-LAST:event_InvestigadoresActionPerformed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
        Descripcion.transferFocus();
    }//GEN-LAST:event_DescripcionActionPerformed

    private void VentajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentajasActionPerformed
        // TODO add your handling code here:
        Ventajas.transferFocus();
    }//GEN-LAST:event_VentajasActionPerformed

    private void AntecedentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntecedentesActionPerformed
        // TODO add your handling code here:
        Antecedentes.transferFocus();
    }//GEN-LAST:event_AntecedentesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void AplicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicacionesActionPerformed
        // TODO add your handling code here:
        Aplicaciones.transferFocus();
    }//GEN-LAST:event_AplicacionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Conectar con= new Conectar();
       con.conexion();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfertasTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfertasTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfertasTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfertasTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfertasTec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Antecedentes;
    private javax.swing.JTextField Aplicaciones;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Estatus;
    private javax.swing.JTextField Investigadores;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Ventajas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
