/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbasesav_p1;

import java.sql.Connection;
import java.sql.ResultSet;
import com.mysql.jdbc.Statement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import structures.Cluster;
import structures.Institucion;
import structures.Investigador;
import structures.Oficina;
import structures.Proyecto;

/**
 *
 * @author Cousik94
 */
public class Registro extends javax.swing.JFrame {

    int idInst;
    Oficina[] oficinas;
    Cluster[] clusters;
    String nombre;
    String ventaja;
    String antecedentes;
    String descripcion;
    String estatus;
    String aplicaciones;
    ArrayList<Investigador> invs;
    Proyecto p;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    public Registro(String nombre, String ventajas, String antecedentes, String descripcion, String estatus, String aplicaciones, ArrayList<Investigador> invs) {
        this.nombre = nombre;
        this.ventaja = ventajas;
        this.antecedentes = antecedentes;
        this.descripcion = descripcion;
        this.estatus = estatus;
        this.aplicaciones = aplicaciones;
        this.invs = invs;
        initComponents();

        anteP.setText(antecedentes);
        descP.setText(estatus);
        nombreP.setText(nombre);
        ventajasP.setText(ventajas);
        descP.setText(descripcion);
        aplicacionesP.setText(aplicaciones);
        estatusP.setText(estatus);
        for (Investigador i : invs) {
            ((CustomTableModel) jTable1.getModel()).addRow(new String[]{i.toString()});
        }

    }

    public Registro(Proyecto p) {
        anteP.setText(p.getAntecedentes());
        descP.setText(p.getDescripcion());
        nombreP.setText(p.toString());
        ventajasP.setText(p.getVentajas());
        descP.setText(p.getDescripcion());
        aplicacionesP.setText(p.getAplicaciones());
        estatusP.setText(p.getEstatus());
        this.p = p;
        Connection con;
        try {
            con = Conexion.getConexion();
           for (int i : p.getIdInvestigadores()) {
                ResultSet rs =Conexion.consultValues(con, "select nombre from Investigadores where idInvestigadores = ?", new Object[]{i});
                rs.next();
                ((CustomTableModel) jTable1.getModel()).addRow(new Object[]{rs.getString(1)});
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
    }

    public Proyecto formulario;

    Registro(int idInstitucion) {
        idInst = idInstitucion;
        try {
            Connection con = Conexion.getConexion();
            oficinas = Conexion.rstoOficinas(con, "select * from oficina where idOficina=?", new Object[]{idInst});
            clusters = Conexion.rstoClusters(con, "select * from cluster where fkOficina=?", new Object[]{oficinas[0].getId()});
            updateComboBoxes(2);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        agregarInv = new javax.swing.JButton();
        creatP = new javax.swing.JButton();
        nombreP = new javax.swing.JTextField();
        descP = new javax.swing.JTextField();
        estatusP = new javax.swing.JTextField();
        ventajasP = new javax.swing.JTextField();
        anteP = new javax.swing.JTextField();
        aplicacionesP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cluster = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        oficina = new javax.swing.JComboBox<String>();
        creatP1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/logo2.png"))); // NOI18N

        agregarInv.setText("Agregar Investigador");
        agregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInvActionPerformed(evt);
            }
        });

        creatP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        creatP.setText("Crear Proyecto");
        creatP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatPActionPerformed(evt);
            }
        });

        nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePActionPerformed(evt);
            }
        });

        ventajasP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventajasPActionPerformed(evt);
            }
        });

        jLabel8.setText("Colaboradores");

        jLabel7.setText("Aplicaciones");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Antecedentes");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Registra el Proyecto");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Descripción");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Estatus");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Ventajas");

        jTable1.setModel(new CustomTableModel("investigadores"));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Cluster");

        cluster.setModel(new javax.swing.DefaultComboBoxModel(clusters!=null ? clusters : new Cluster[]{} ));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Oficina:");

        oficina.setModel(new javax.swing.DefaultComboBoxModel(oficinas!=null?oficinas:new Oficina[]{}));
        oficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficinaActionPerformed(evt);
            }
        });

        creatP1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        creatP1.setText("Actualizat");
        creatP1.setEnabled(false);
        creatP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(oficina, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(cluster, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aplicacionesP, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(agregarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creatP)
                .addGap(227, 227, 227))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 68, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(logo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(anteP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(estatusP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ventajasP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 69, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(433, Short.MAX_VALUE)
                    .addComponent(creatP1)
                    .addGap(232, 232, 232)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarInv)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(aplicacionesP, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(creatP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 84, Short.MAX_VALUE)
                    .addComponent(logo)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel1)
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel5)
                            .addGap(47, 47, 47)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(descP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel6))
                        .addComponent(anteP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel3)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(estatusP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ventajasP, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 136, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(598, Short.MAX_VALUE)
                    .addComponent(creatP1)
                    .addGap(10, 10, 10)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePActionPerformed

    private void ventajasPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventajasPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventajasPActionPerformed

    private void creatPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatPActionPerformed
        // TODO add your handling code here:

        String SQL = "INSERT INTO `ofertas_tecnologicas` Values(?,?,?,?,?,?,?,?)";
        String sql2 = "insert into ofertas_Tecnologicas_has_Investigadores Values(?,?); ";

        try {
            Connection con = Conexion.getConexion();

            Conexion.executeUpdate(con, SQL, new Object[]{Conexion.getAutonumericField(con, SQL, 1), ((Cluster) cluster.getSelectedItem()).getId(), nombreP.getText(), descP.getText(), estatusP.getText(), ventajasP.getText(), anteP.getText(), aplicacionesP.getText()});
            if(invs!=null)
            for (Investigador i : invs) {
                Conexion.executeUpdate(con, sql2, new Object[]{Conexion.consultValues(con, "select idOT from ofertas_Tecnologicas where nombre= ?", new Object[]{nombre}).getInt(1), i.getId()});
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_creatPActionPerformed

    private void agregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInvActionPerformed
        // TODO add your handling code here:
        cambiarVentana(new Investigadores(nombre, ventaja, antecedentes, descripcion, estatus, aplicaciones));
    }//GEN-LAST:event_agregarInvActionPerformed

    private void oficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficinaActionPerformed
        try {
            Connection con = Conexion.getConexion();
            clusters = Conexion.rstoClusters(con, "select * from cluster where fkOficina=?", new Object[]{((Oficina) oficina.getSelectedItem()).getId()});
            updateComboBoxes(3);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_oficinaActionPerformed

    private void creatP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatP1ActionPerformed
        String SQL = "INSERT INTO `ofertas_tecnologicas` Values(?,?,?,?,?,?,?,?)";
        String sql2 = "insert into ofertas_Tecnologicas_has_Investigadores Values(?,?); ";

        try {
            Connection con = Conexion.getConexion();

            Conexion.consultValues(con, SQL, new Object[]{Conexion.getAutonumericField(con, SQL, 1), ((Cluster) cluster.getSelectedItem()).getId(), nombre, descripcion, estatus, ventaja, antecedentes, aplicaciones});
            for (Investigador i : invs) {
                Conexion.consultValues(con, sql2, new Object[]{Conexion.consultValues(con, "select idOT from ofertas_Tecnologicas where nombre= ?", new Object[]{nombre}).getInt(1), i.getId()});
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_creatP1ActionPerformed
    public void cambiarVentana(JFrame frame) {
        frame.setVisible(true);
        this.dispose();
    }

    void updateComboBoxes(int c) {
        switch (c) {
            case 2:
                if (oficinas != null) {
                    oficina.setModel(new DefaultComboBoxModel(oficinas));
                } else {
                    oficina.setModel(new javax.swing.DefaultComboBoxModel(new Oficina[]{}));
                    oficina.setEnabled(false);
                    cluster.setEnabled(false);
                }

            case 3:
                if (clusters != null) {
               cluster.setModel(new javax.swing.DefaultComboBoxModel(clusters));
                } else {
                    cluster.setModel(new javax.swing.DefaultComboBoxModel(new Cluster[]{}));
                    cluster.setEnabled(false);
                }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarInv;
    private javax.swing.JTextField anteP;
    private javax.swing.JTextField aplicacionesP;
    private javax.swing.JComboBox<String> cluster;
    private javax.swing.JButton creatP;
    private javax.swing.JButton creatP1;
    private javax.swing.JTextField descP;
    private javax.swing.JTextField estatusP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logo;
    private javax.swing.JTextField nombreP;
    private javax.swing.JComboBox<String> oficina;
    private javax.swing.JTextField ventajasP;
    // End of variables declaration//GEN-END:variables
}
