/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbasesav_p1;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import structures.Cluster;
import structures.Institucion;
import structures.Oficina;
import structures.Proyecto;

/**
 *
 * @author fangi
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
   
        Institucion[] instutuciones;
    Oficina[] oficinas;
    Cluster[] clusters;
    Proyecto[] proyectos;
       public void cambiarVentana(JFrame frame) {
        frame.setVisible(true);
        this.dispose();
    }
    public Start() {
       try {
            Connection con = Conexion.getConexion();
            
        instutuciones=Conexion.rstoInstituciones(con, "select * from institucion ", null);
        } catch (SQLException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        RegistroP = new javax.swing.JButton();
        logo = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        crearP = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        buscar = new javax.swing.JTextField();
        institucion = new javax.swing.JComboBox<>();
        oficina = new javax.swing.JComboBox<>();
        cluster = new javax.swing.JComboBox<>();
        ChechBInv = new javax.swing.JCheckBox();
        CheckBOT = new javax.swing.JCheckBox();
        Resultados = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 25, -1, -1));

        Buscar.setText("Buscar");
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 359, -1, -1));

        RegistroP.setForeground(new java.awt.Color(60, 63, 65));
        RegistroP.setText("Registro Proyecto");
        RegistroP.setBorderPainted(false);
        RegistroP.setEnabled(false);
        RegistroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroPActionPerformed(evt);
            }
        });
        getContentPane().add(RegistroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 91, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Login/logo2.png"))); // NOI18N
        logo.setBorderPainted(false);
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 359, -1, -1));

        modificar.setText("Modificar");
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        crearP.setForeground(new java.awt.Color(60, 63, 65));
        crearP.setText("Crear Proyecto");
        crearP.setBorderPainted(false);
        crearP.setEnabled(false);
        getContentPane().add(crearP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 29, 78, -1));
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 29, 79, -1));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 301, 255, -1));

        institucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        institucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institucionActionPerformed(evt);
            }
        });
        getContentPane().add(institucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 170, 190, -1));

        oficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(oficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 214, 190, -1));

        cluster.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cluster, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 255, 190, -1));

        ChechBInv.setText("Investigadores");
        ChechBInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChechBInvActionPerformed(evt);
            }
        });
        getContentPane().add(ChechBInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 301, -1, -1));

        CheckBOT.setText("OT´s");
        getContentPane().add(CheckBOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 301, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Proyecto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Resultados.setViewportView(jScrollPane1);

        getContentPane().add(Resultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 409, 525, 230));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 33, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Instituciones:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Oficina:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 212, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Clusters");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 254, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Buscar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 299, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void ChechBInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChechBInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChechBInvActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void RegistroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroPActionPerformed

    private void institucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_institucionActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JCheckBox ChechBInv;
    private javax.swing.JCheckBox CheckBOT;
    private javax.swing.JButton Login;
    private javax.swing.JButton RegistroP;
    private javax.swing.JScrollPane Resultados;
    private javax.swing.JTextField buscar;
    private javax.swing.JComboBox<String> cluster;
    private javax.swing.JTextField contraseña;
    private javax.swing.JButton crearP;
    private javax.swing.JButton eliminar;
    private javax.swing.JComboBox<String> institucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logo;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox<String> oficina;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
